- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
   - name: Download Licence file
     get_url:
        url: https://www.opentlc.com/download/ansible_bootcamp/tower/licenses/license.txt
        dest: /tmp/license.txt
   - name: Append file
     lineinfile:
        path: /tmp/license.txt
        insertbefore: '"company_name.*"'
        line: '"eula_accepted" : "true",'
