- hosts: tag_AnsibleGroup_bastions
  gather_facts: true
  become: true
  tasks:
  - name: List key files
    shell: (cd /root/.ssh; find . -maxdepth 1 -type f -iname '*key.pem')| cut -d'/' -f2
    register: file_to_copy
  - debug: var=file_to_copy 
  - name: Copy key file
    fetch:
     src: "/root/.ssh/{{item}}"
     dest: /tmp/
     flat: yes
    loop: "{{ file_to_copy.stdout }}" 
